### ISSUE TITLE
Configurable player URL options

### ISSUE THREAD

**Issue by groe** [Staplegun-US/craft-video-embed-utility#12]
On youtube it's possible to remove the suggested videos at the end of the video by adding `&rel=0` to the player url. It would be cool if the plugin supported custom options like this.

**Comment by kotyy** [comment]
I believe `{{ url|videoEmbed({ rel: 1}) }}` should work. Can you give it a shot?

**Comment by groe** [comment]
It works - cool! I somehow missed that this is possible.

Btw, does this do anything to other video provider embed codes, such as vimeo?

**Comment by kotyy** [comment]
Yup. The filter takes the provided options and [builds them into a query string](https://github.com/Staplegun-US/craft-video-embed-utility/blob/master/videoembedutility/twigextensions/VideoEmbedUtilityTwigExtension.php#L105), which is appended to the end of the used URL for the embed.
