### ISSUE TITLE
Youtube `controls` parameter not configurable

### ISSUE THREAD

**Issue by groe** [Staplegun-US/craft-video-embed-utility#15]
Hi!

For youtube the plugin currently uses `//www.youtube.com/embed/$videoId?controls=2` as the player URL. Now when calling `videoEmbed({controls: 1})`, the resulting URL is `//www.youtube.com/embed/$videoId?controls=2&controls=1` - which does not work.

Can we make `controls` configurable? Also, I wonder why controls=2 is even there? Shouldn't we just default to youtubes embed defaults (i.e. provide no specific parameters if none are passed to `videoEmbed`)?

**Comment by rayhatfield** [comment]
Default controls parameter has been removed.
