### ISSUE TITLE
Legacy videos no longer rendering on site using "https://www.youtube.com/watch?v=_nfREkI8Nsk" format

### ISSUE THREAD

**Issue by Alistewart253** [Staplegun-US/craft-video-embed-utility#20]
We've noticed that videos are no longer rendering on any site pages they were previously. The format of the link being used is "https://www.youtube.com/watch?v=_nfREkI8Nsk" but when using the video ID as well the videos do not display. 

Reference URL: https://www.thisispaddington.com/article/an-animated-christmas-treat-from-the-paddington-community-programme

Video should be outputting after the following paragraph:

"Just in time for Christmas, the Paddington Community Programme is excited to deliver our seasonal gift to you. A fun-filled forty seconds of artistic animation that captures what we do and why you should join us in 2018."

![Screenshot 2019-07-31 at 16 40 01](https://user-images.githubusercontent.com/53531978/62226285-decbeb00-b3b1-11e9-8a9b-fc06890ab4e4.png)

![Screenshot 2019-07-31 at 16 36 10](https://user-images.githubusercontent.com/53531978/62226071-85fc5280-b3b1-11e9-963c-0ba46b1d947c.png)

Have there been any updates to the required link formats that we need to be aware of?

Thanks for your help.

**Comment by rayhatfield** [comment]
Hey @Alistewart253 — I wanted to acknowledge that I saw this issue but let you know that I may not get to it anytime soon. If you're inclined to look at it yourself I suspect it may be caused by an inability to identify the video id, which happens [on line 52 in VideoEmbedUtilityTwigExtension](https://github.com/Staplegun-US/craft-video-embed-utility/blob/master/videoembedutility/twigextensions/VideoEmbedUtilityTwigExtension.php#L52).

**Comment by Alistewart253** [comment]
Thanks for letting me know Ray.
We've managed to solve it. Thanks for your help.
Will update this with the exact fix shortly.



Alastair Stewart
Managing Director

07786903305
www.studiotreble.com

**Comment by rayhatfield** [comment]
Did you identify the issue? Would it be a generally useful change? If so, submit a pull request and I'l merge it in.

**Comment by Alistewart253** [comment]
Issue was an error at our side I'm afraid. No need to merge. Many thanks for your time.
